- frappe_io/templates/includes/footer/footer.html
This commits adds separate footer to frappe io, the common footer used from the frappe_theme is now removed.
> Add separate footer

- .gitignore
- README.md
- frappe_io/hooks.py
- frappe_io/templates/includes/blog/blog.html
- frappe_io/templates/includes/custom.css
- frappe_io/templates/includes/footer/footer.html
- frappe_io/www/about.html
- frappe_io/www/index.html
- frappe_io/www/jobs.md
- frappe_io/www/story.md
- frappe_io/www/terms.md
This PR removes excess padding from the blog page container.
> Remove padding from the blog page container & change name from Frappé to Frappe

- frappe_io/www/frappe/index.html
Fixed typo in doctype description
> Typo Fix "everwhere" to "everywhere"

- frappe_io/www/docs/user/en/guides/app-development/overriding-link-query-by-custom-script.md
- frappe_io/www/docs/user/en/guides/basics/apps.md
- frappe_io/www/docs/user/en/guides/basics/hooks.md
- frappe_io/www/docs/user/en/guides/basics/site_config.md
- frappe_io/www/docs/user/en/guides/basics/sites.md
- frappe_io/www/docs/user/en/tutorial/start.md
Following corrections were made:
- The URL to the Digital Ocean tutorial was turned into a hyperlink with a display text and an extra newline added before the list to ensure it was rendered correctly.
- Minor spelling change ( from `fitlers` to `filters`)
- Corrected command from `make-app` (probably deprecated) to `new-app` (current)
- `site_dr` changed to `sites`, however not sure about the environment variable. Added new section for making a site the currentsite
> Documentation corrections

- frappe_io/www/docs/user/en/guides/basics/site_config.md
Add missing documentation on disabling `socketio`
> guides/basics/site_config: Add `disable_async` docs

- frappe_io/www/charts/docs/basic/trends_regions.md
Hello,
I noticed that using "areaFill" doesn't generate the fill effect as shown below:
Replacing it with "regionFill" works:
Cheers,
Shesh
> Replaced "areaFill" to "regionFill" as the former doesn't work

- frappe_io/www/docs/user/en/tutorial/doctypes.md
Replacing the command since ```bench mysql``` command has been deprecated and replaced by `bench mariadb`
> [Docs] Change 'bench mysql' command to 'bench mariadb'

- frappe_io/www/docs/user/en/guides/integration/rest_api/index.md
Fix grammar in first sentence, split introduction into sections "RPC" and "REST".
> Fix and improve introduction to API

- frappe_io/www/docs/user/en/guides/integration/rest_api/simple_authentication.md
Escape underscores to avoid inappropriate italics.
> Escape underscores in API docs

- frappe_io/www/docs/user/en/tutorial/naming-and-linking.md
I am not sure since what revision this was changed. But if it is not working if set the linked doctype field in Option, this is misleading for newbie like me when starting with the tutorial.
> Set in Option for Read Only field is not working

- frappe_io/www/docs/user/en/bench/resources/bench-commands-cheatsheet.md
Add the path where backup can be found: `~/frappe-bench/sites/{your site}/private/backups/`
> Add backup path to bench cheatsheet

- frappe_io/www/docs/user/en/tutorial/setting-up-the-site.md
- Barracuda is a file format, not a storage engine. InnoDB is the storage engine that supports Barracuda file format. 😄
> Update Setting Up The Site section in docs

- frappe_io/www/charts/docs/reference/configuration.md
I recognized a small error in the documentation: `barOptions.spaceRatio` max value is 1 and not 2. Using a value over 1 always throws an error. e.g. `Error: <rect> attribute width: A negative value is not valid. ("-11.742857142857153")`
> Fix docs about barOptions.spaceRatio max value

- frappe_io/www/docs/user/en/api/form.md
The correct order is `{fieldname}` on which you want to apply filter and then the `{child_table_fieldname}`
> docs: Fix set_query for child table fields

- frappe_io/www/charts/docs/index.md
Because Uncaught ReferenceError: Chart is not defined
> Fix Chart is not defined

- frappe_io/www/docs/user/en/tutorial/bench.md
Please add the bench init step, I was not able to follow it, it felt like disconnect because the next step (https://frappe.io/docs/user/en/tutorial/new-app) wasn't working. I had to look somewhere else for the answer.
> Missing step for the next section

- frappe_io/www/charts/docs/wrappers.md
📈 Add [svelte-frappe-charts](https://github.com/himynameisdave/svelte-frappe-charts) to wrappers.
> 📈 Add svelte-frappe-charts to wrappers

- frappe_io/www/docs/user/en/tutorial/naming-and-linking.md
> docs: Fix Typo in "naming-and-linking"

- frappe_io/www/docs/user/en/understanding-doctypes.md
`moret than 30` to `more than 30`.
> docs: Fix typo in line 171

- frappe_io/www/docs/user/en/api/document.md
Comment example has an additional parentheses.
> docs: Fix minor error in comment example

- frappe_io/www/docs/user/en/installation.md
Fix 404 'not found' link
Change from this:
https://frappe.io/docs/installation/architecture
to this: 
https://frappe.io/docs/user/en/architecture
> docs: Update installation.md

- frappe_io/templates/includes/footer/footer.html
New page for Team: https://frappe.io/team
> fix: Replace link of Team (/team)

- frappe_io/www/docs/user/en/translations.md
Add info for no trailing space in translatable string.
> docs: Add info for no trailing space in translatable string

- frappe_io/www/docs/user/en/api/dialog.md
Explaining the usage of frappe.hide_progress()
> Usage of frappe.hide_progress()

- frappe_io/www/docs/user/en/_sidebar.json
The current url is wrong, sending the user to a blank page for an important piece of information.
> docs: Update en/sidebar entry for deployment

- frappe_io/website_context.py
**Fixes**
When this context updation gets executed via a background job(ex.print format for invoicing) it breaks during runtime with ``` RuntimeError: no object bound to request ```
> fix: check request object
