- frappe_io/www/help/how-to/git-help-contribute.md
- frappe_io/www/help/how-to/index.txt
Beginners guide to start contributing
> HOWTO: Git Help - Contribute

- frappe_io/www/tutorial/doctype-directory-structure.md
- frappe_io/www/tutorial/doctypes.md
- frappe_io/www/tutorial/form-client-scripting.md
- frappe_io/www/tutorial/new-app.md
- frappe_io/www/tutorial/roles.md
Hi guys!
During playing with the tutorial, I fought a little bit with the "custom" field and I noticed some little typos and out-of-date things. So here is some commits fixing this.
Thanks for your amazing work!
> Custom field highlight, typos and update

- frappe_io/www/docs/user/en/guides/basics/sites.md
- frappe_io/www/docs/user/en/tutorial/form-client-scripting.md
- frappe_io/www/docs/user/es/tutorial/form-client-scripting.md
- frappe_io/www/docs/user/fr/tutorial/form-client-scripting.md
- frappe_io/www/docs/user/pt/tutorial/form-client-scripting.md
/frappe/user/ should be renamed /docs/user/
> Update error link

- frappe_io/www/about.html
080-339-23819 to +91-80-339-23819
> Updated Contact Number in international format

- frappe_io/public/build.json
Not needed to build on every build.
> remove docs.js build config

- frappe_io/www/frappe/index.html
- frappe_io/www/security.md
Signed-off-by: Chinmay Pai <chinmaydpai@gmail.com>
> security: add a page for security vulnerabilities and exploits

- frappe_io/www/docs/user/en/tutorial/task-runner.md
datediff doesn't exist, changed to date_diff
> Tutorial Fixes

- frappe_io/www/docs/user/en/guides/app-development/how-enable-developer-mode-in-frappe.md
After following all of the steps in the tutorial, I still didn't get my Developer icon on the Desktop.
> Clarify final step

- frappe_io/www/docs/user/en/guides/integration/rest_api/index.md
> Removing author credits

- frappe_io/www/careers/apply.md
> Revert "Change email from 'hello' to 'jobs' for applicants"

- frappe_io/www/docs/user/en/guides/basics/hooks.md
https://discuss.erpnext.com/t/on-update-vs-after-save/44866
> removed after_save event

- frappe_io/www/docs/user/en/guides/app-development/how-enable-developer-mode-in-frappe.md
Add bench config command:
`bench set-config developer_mode 1`
> fix(docs): Update "How to Enable Developer Mode"

- frappe_io/www/docs/user/en/guides/integration/how_to_set_up_token_based_auth.md
Added missing function name to RPC call path and bench command path.
> Add full path to RPC and bench command path.

- frappe_io/www/about.html
Clicking on Skype username will now open the chat in the app directly.
> feat: add direct link for Skype

- frappe_io/www/docs/user/en/guides/integration/webhooks.md
Documentation update for https://github.com/frappe/frappe/pull/8264.
> docs: Update webhook documentation

- frappe_io/frappe_team/doctype/frappe_job_applicant/frappe_job_applicant.json
- frappe_io/frappe_team/web_form/join_us/join_us.json
> feat: Add mobile no. as mandatory field to join-us form

- frappe_io/www/docs/user/en/api/document.md
> docs: Update Document API docs

- frappe_io/www/docs/user/en/bench/resources/bench-commands-cheatsheet.md
Add useful `bench init` parameters info
> Parameter Info for bench init

- frappe_io/www/docs/user/en/guides/app-development/overriding-link-query-by-custom-script.md
in JavaScript array you cannot use ":"
> syntax error in example code

- frappe_io/www/docs/index.md
Updated broken link to installation guide.
> Fix: broken link to Installation

- frappe_io/www/docs/user/en/tutorial/form-client-scripting.md
I found the unedited code to be not working, the "library_member" should've been inside an object, not as a second parameter... Please correct me if I'm wrong
> On insert library member change

- frappe_io/www/docs/user/en/tutorial/web-views.md
Improving the syntax by describing the difference between Desk UI and web.
> Improving text readability in Web views

- frappe_io/www/docs/user/en/tutorial/form-client-scripting.md
Editing the first paragraph under "Client Side Scripting" title.
> Fix: Improve the Description text for Client Side Scripting

- frappe_io/www/docs/user/en/guides/portal-development/contents.md
... and info about how they're rendered.
> Escape {next} and {index}

- frappe_io/www/docs/user/en/index.md
- frappe_io/www/docs/user/en/integration/razorpay/index.md
Documentation for https://github.com/frappe/frappe/pull/8808
> feat: added docs for razorpay client checkout

- frappe_io/hooks.py
Redirects for bench documentation
> chore: added bench documentation redirects

- frappe_io/www/docs/user/en/guides/automated-testing/qunit-testing.md
> Fix path to image

- frappe_io/www/docs/user/en/bench/resources/bench-commands-cheatsheet.md
refer: https://github.com/frappe/frappe/pull/8874
> docs: add db_host and db_port options for new-site

- frappe_io/www/docs/user/en/guides/basics/hooks.md
Docs for jinja customization hooks
> docs: jinja customisation hooks

- frappe_io/www/docs/user/en/apps.md
> docs: fix link for module

- frappe_io/www/docs/user/en/understanding-doctypes.md
Examples for depends_on properties
> docs: add examples for depends_on properties

- frappe_io/www/docs/user/en/guides/basics/hooks.md
Documentation for https://github.com/frappe/frappe/pull/8905 added
pull request depneds on https://github.com/frappe/frappe/pull/8905
> docs: auto_cancel_exempted_doctypes hook

- frappe_io/www/docs/user/en/guides/integration/webhooks.md
Reference for https://github.com/frappe/frappe/pull/9244.
> docs: webhook security

- frappe_io/www/flask-test.md
updated flask test mentioning focus on UI
> feat: flask test improvements

- frappe_io/www/bench/index.md
> chore: update bench docs

- frappe_io/www/docs/user/en/bench/resources/bench-commands-cheatsheet.md
I've added description for bench upadate --reset switch.
> bench update --reset switch was missing in documentation.

- frappe_io/www/docs/user/en/guides/app-development/trigger-event-on-deletion-of-grid-row.md
> docs: Fix code snippets

- frappe_io/www/docs/user/en/debugging.md
- frappe_io/www/docs/user/en/sites.md
Docs for Frequent job scheduling and Monitor
> docs: Frequent job scheduling and Monitor

- frappe_io/www/docs/user/en/tutorial/conclusion.md
Gitter room no longer exists, removed.
> docs: Remove Gitter link

- frappe_io/www/docs/user/en/guides/basics/frappe_ajax_call.md
> docs: Update frappe_ajax_call.md

- frappe_io/www/docs/user/en/reports.md
> feat: added script report api reference

- frappe_io/www/about.html
- frappe_io/www/contact.html
- frappe_io/www/contact.py
> feat: new about and contact pages

- frappe_io/www/docs/user/en/guides/basics/hooks.md
**Ref:** https://github.com/frappe/frappe/pull/9610
> docs: add info for new Web Form hooks

- frappe_io/www/docs/user/en/reports.md
> docs: depends_on property for script report filters (v13)

- frappe_io/www/docs/user/en/installation.md
- frappe_io/www/docs/user/en/production-setup.md
* add docker
* update nvm
* update brew link
* update wkhtmltopdf
* install bench with pip
> chore: update bench installation guide

- frappe_io/www/docs/user/en/bench/resources/bench-commands-cheatsheet.md
relevant PR: frappe/frappe#9685
> chore: add documentation for db-password in new-site

- frappe_io/www/docs/user/en/guides/integration/how_to_set_up_oauth.md
Updated docs related to OAuth Client
https://github.com/frappe/frappe/pull/7610
> update: oauth2 client docs

- frappe_io/www/docs/user/en/guides/integration/social_login_key.md
Documentation for https://github.com/frappe/frappe/pull/7650
> update: Social Login Keys Docs

- frappe_io/www/docs/user/en/translations.md
> docs: Add contextual translation docs

- frappe_io/www/docs/user/en/reports.md
Docs for [#10357](https://github.com/frappe/frappe/pull/10357)
> Update Docs for frappe#10357

- frappe_io/www/docs/user/en/understanding-doctypes.md
Against https://github.com/frappe/frappe/pull/10116
> docs: section break without border

- frappe_io/hooks.py
- frappe_io/patches.txt
- frappe_io/website_context.py
- frappe_io/www/datatable/index.html
- frappe_io/www/frappejs/index.html
- frappe_io/www/gantt/index.html
- Update broken links
- Delete Book doctype (wtf is this)
> fix: Update context for doc pages

- frappe_io/hooks.py
- frappe_io/public/docs/charts.js
- frappe_io/www/charts/index.html
* Don't include charts demo script in every page
> perf: dont load chart demo script on every web page 
